version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    labels:
      - "traefik.frontend.rule=Host:magento2.localhost"
    environment:
      - VIRTUAL_HOST=magento2.localhost
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 80
    links:
      - web
    networks:
      - traefik_default

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - 80
    links:
      - fpm
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    #environment:
      #- VIRTUAL_HOST=magento2.localhost
      #- VIRTUAL_PORT=80
      #- HTTPS_METHOD=noredirect
    networks:
      - traefik_default

  fpm:
    labels:
      - "traefik.frontend.rule=Host:fpm.magento2.localhost"
    hostname: fpm.magento2.localhost
    image: meanbee/magento2-php:7.1-fpm
    ports:
      - 9000
    links:
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    networks:
      - traefik_default

  db:
    image: mariadb:10
    ports:
      - 3306
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh
    networks:
      - traefik_default

  cli:
    labels:
      - "traefik.frontend.rule=Host:cli.magento2.localhost"
    hostname: cli.magento2.localhost
    image: meanbee/magento2-php:7.1-cli
    links:
      - db
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2.localhost/
      - M2SETUP_SECURE_BASE_URL=https://magento2.localhost/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.2.*
      - M2SETUP_USE_SAMPLE_DATA=true
    networks:
      - traefik_default

  cron:
    image: meanbee/magento2-php:7.1-cli
    labels:
      - "traefik.frontend.rule=Host:magento2-cron.docker"
    hostname: magento2-cron.localhost
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db
    env_file:
      - ./global.env      
    networks:
      - traefik_default

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/magento
    networks:
      - traefik_default

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
    networks:
      - traefik_default
      
networks:
  traefik_default:
    external:
      name: traefik_default
